server:
  context-path: /
  port: 8080
  
mapperLocationPattern: /mybatis/mapper/*.xml

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations:
  - /mybatis/mapper/*.xml

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.31.244:3306/shop01?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
    
    schema:
#      - classpath:sql/test.sql
#      - classpath:sql/employee.sql
    